# Generated by Django 3.0 on 2019-12-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headline', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('pub_date', models.DateField(null=True)),
                ('number_of_comments', models.IntegerField(default=0)),
                ('number_of_lines', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='queryset.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryset.Blog')),
            ],
        ),
    ]
