# Generated by Django 3.0 on 2019-12-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0002_auto_20191223_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childa',
            name='m2m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_childa', to='abstract.Student'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='m2m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstract_childb', to='abstract.Student'),
        ),
    ]
