# Generated by Django 3.0 on 2019-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0005_auto_20191219_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='to_user',
            new_name='counterpart',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='from_user',
            new_name='me',
        ),
    ]
